service: apollo-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  profile: 4life
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 512
  timeout: 6
  environment:
    STAGE: ${opt:stage, 'dev'}

package:
  excludeDevDependencies: true

functions:
  graphql:
    handler: index.handler
    name: apollo-lambda-${opt:stage, 'dev'}
    description: Graphql API function for nft marketplace lambda.Digital
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true

custom:
  serverless-offline:
    httpPort: 3005
    noPrependStageInUrl: true
